# Generated by Django 4.2.15 on 2024-08-26 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('home_store', models.CharField(max_length=100)),
                ('customer_first_name', models.CharField(max_length=50)),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_since', models.DateField()),
                ('loyalty_card_number', models.CharField(max_length=15)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('birth_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_group', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=40)),
                ('product_type', models.CharField(max_length=40)),
                ('product', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=200)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('current_wholesale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_exempt_yn', models.CharField(max_length=1)),
                ('promo_yn', models.CharField(max_length=1)),
                ('new_product_yn', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOutlet',
            fields=[
                ('sales_outlet_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sales_outlet_type', models.CharField(max_length=20)),
                ('store_square_feet', models.IntegerField()),
                ('store_address', models.CharField(max_length=150)),
                ('store_city', models.CharField(max_length=50)),
                ('store_state_province', models.CharField(max_length=2)),
                ('store_telephone', models.CharField(max_length=15)),
                ('store_postal_code', models.CharField(max_length=10)),
                ('store_latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('store_longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('manager', models.CharField(max_length=40)),
                ('neighborhood', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SalesReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('transaction_date', models.DateField()),
                ('transaction_time', models.DateTimeField()),
                ('staff_id', models.IntegerField()),
                ('instore_yn', models.CharField(max_length=1)),
                ('order', models.IntegerField()),
                ('line_item_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('line_item_amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('promo_item_yn', models.CharField(default='N', max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.product')),
                ('sales_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.salesoutlet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='salesreceipts',
            constraint=models.UniqueConstraint(fields=('transaction_id', 'transaction_date', 'transaction_time', 'sales_outlet'), name='unique_field1_field2'),
        ),
    ]
