# Generated by Django 4.2.15 on 2024-08-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_salesoutlet_store_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreceipts',
            name='line_item_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='salesreceipts',
            name='line_item_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesreceipts',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesreceipts',
            name='promo_item_yn',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='salesreceipts',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesreceipts',
            name='staff_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesreceipts',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
