# Generated by Django 4.2.15 on 2024-08-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_salesreceipts_line_item_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesreceipts',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='salesreceipts',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='salesreceipts',
            old_name='sales_outlet_id',
            new_name='sales_outlet',
        ),
    ]
