# Generated by Django 4.2.15 on 2024-08-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_customer_id_salesreceipts_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesReceipts',
        ),
    ]
