# Generated by Django 4.2.15 on 2024-08-25 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_delete_salesreceipts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReceipts',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('transaction_time', models.DateTimeField()),
                ('staff_id', models.IntegerField(default=0)),
                ('instore_yn', models.CharField(max_length=1)),
                ('order', models.IntegerField(default=0)),
                ('line_item_id', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('line_item_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('promo_item_yn', models.CharField(default='N', max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.product')),
                ('sales_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.salesoutlet')),
            ],
        ),
    ]
