# Generated by Django 4.2.15 on 2024-08-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_salesreceipts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesReceipts',
        ),
    ]
